# Generated by Django 4.2.16 on 2024-11-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
    ]
