services:
  db:
    image: mysql:8.0
    container_name: django_dancina_db
    volumes:
      - ./docker-mysql-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=230223  # Set this password
      - MYSQL_DATABASE=dancina_db
  django:
    build: .
    container_name: django_dancina
    command: >
      sh -c "
             python /eventcalendar/manage.py collectstatic --noinput &&
             python /eventcalendar/manage.py makemigrations --no-input &&
             python /eventcalendar/manage.py migrate --no-input &&
             gunicorn eventcalendar.wsgi --bind 0.0.0.0:8001 --workers 2
            "
    ports:
      - "8001:8000"
    volumes:
      - .:/eventcalendar
    env_file:
      - .env
    depends_on:
      - db


networks:
  default:
    driver: bridge
    name: dancina_network