# Generated by Django 4.2.16 on 2024-11-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
   
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=100, null=True)),
                ('is_member', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('TOTAL', 'Total Payment'), ('PARTIAL', 'Partial Payment')], max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_left', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('classes_attended', models.PositiveIntegerField(default=0)),
                ('classes_left', models.PositiveIntegerField()),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='calendarapp.event')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='clients.client')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendarapp.package')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='classes',
            field=models.ManyToManyField(related_name='clients', through='clients.Registration', to='calendarapp.event'),
        ),
    ]
