# Generated by Django 4.2.16 on 2024-11-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_instructor_package_studiolocation_event_instructor_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='classes',
            field=models.ManyToManyField(related_name='clients', through='clients.Registration', to='calendarapp.event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='calendarapp.event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendarapp.package'),
        ),
    ]
