# Generated by Django 4.2.16 on 2025-01-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_type',
            field=models.CharField(choices=[('TOTAL', 'Full Payment'), ('PARTIAL', 'Partial Payment')], max_length=20),
        ),
    ]
