# Generated by Django 4.2.16 on 2024-11-27 10:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_remove_event_description_remove_event_title_and_more'),
        ('clients', '0002_alter_client_classes_alter_registration_class_obj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='note',
        ),
        migrations.AddField(
            model_name='registration',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendarapp.packagetype'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('VISA', 'Visa'), ('CASH', 'Cash'), ('INSTAPAY', 'Instapay')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be up to 11 digits and numeric only.', regex='^\\d{1,11}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='preferred_time',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
