# Generated by Django 4.2.16 on 2024-12-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_receipt_number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
