# Generated by Django 4.2.16 on 2024-12-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_transactionsettings_alter_transaction_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='expiration_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
