# Generated by Django 4.2.16 on 2024-12-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_registration_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('VISA', 'Visa'), ('CASH', 'Cash'), ('INSTAPAY', 'Instapay')], max_length=10, null=True),
        ),
    ]
