# Generated by Django 4.2.16 on 2024-12-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_registration_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('VISA', 'Visa'), ('CASH', 'Cash'), ('INSTAPAY', 'Instapay')], max_length=10, null=True),
        ),
    ]
