# Generated by Django 4.2.16 on 2024-12-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_remove_registration_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_registration', to='clients.registration'),
        ),
    ]
