# Generated by Django 4.2.16 on 2024-12-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0019_remove_classoccurrence_registrations'),
        ('clients', '0012_transaction_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('class_occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='calendarapp.classoccurrence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='clients.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='calendarapp.event')),
            ],
        ),
    ]
