# Generated by Django 4.2.16 on 2024-12-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_occurrence',
        ),
    ]
