# Generated by Django 4.2.16 on 2025-01-16 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to='clients.client'),
        ),
        migrations.AddField(
            model_name='event',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendarapp.instructor'),
        ),
        migrations.AddField(
            model_name='event',
            name='studio_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendarapp.studiolocation'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classoccurrence',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='calendarapp.event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together={('event', 'user')},
        ),
    ]
