# Generated by Django 4.2.16 on 2025-01-12 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='member_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='non_member_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
