# Generated by Django 4.2.16 on 2025-01-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_alter_package_member_price_per_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
        ),
    ]
