# Generated by Django 4.2.16 on 2025-01-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_privateclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='studio_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendarapp.studiolocation'),
        ),
    ]
