# Generated by Django 4.2.16 on 2024-11-25 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_instructor_package_studiolocation_event_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='share_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
