# Generated by Django 4.2.16 on 2024-11-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_alter_instructor_share_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='studiolocation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
