# Generated by Django 4.2.16 on 2025-01-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_alter_event_studio_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateClass',
        ),
    ]
