# Generated by Django 4.2.16 on 2025-01-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_delete_privateclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoccurrence',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
