# Generated by Django 4.2.16 on 2025-01-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_alter_classoccurrence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
    ]
