# Generated by Django 4.2.16 on 2024-11-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_remove_event_description_remove_event_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='days',
            field=models.CharField(help_text='Comma-separated list of days (e.g., Sunday,Tuesday,Friday)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='from_time',
            field=models.TimeField(help_text='Start time for the class (e.g., 13:00)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='to_time',
            field=models.TimeField(help_text='End time for the class (e.g., 14:00)', null=True),
        ),
    ]
