# Generated by Django 4.2.16 on 2025-01-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_event_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoccurrence',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classoccurrence',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
