# Generated by Django 4.2.16 on 2024-12-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_note_registration_package_type_and_more'),
        ('calendarapp', '0011_remove_event_end_time_remove_event_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to='clients.client'),
        ),
    ]
