# Generated by Django 4.2.16 on 2024-12-09 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0012_alter_eventmember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
