# Generated by Django 4.2.16 on 2024-12-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_transaction_registration'),
        ('calendarapp', '0015_classoccurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoccurrence',
            name='registrations',
            field=models.ManyToManyField(blank=True, related_name='class_occurrences', to='clients.registration'),
        ),
    ]
