# Generated by Django 4.2.16 on 2024-12-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0016_classoccurrence_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_duration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_duration',
            field=models.DateField(null=True),
        ),
    ]
