# Generated by Django 4.2.16 on 2024-12-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0017_event_end_duration_event_start_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
